import type { CommitDiffSchema } from '@gitbeaker/rest'
import type { CoreMessage } from 'ai'
import type { OldFileVersion } from '../routes/gitlab-webhook/services.js'
import type { CommentMode } from '../routes/gitlab-webhook/types.js'

const QUESTIONS = `\n\nQuestions:\n
1. Can you summarize the changes in a succinct bullet point list\n
2. In the diff, are the added or changed code written in a clear and easy to understand way?\n
3. Does the code use comments, or descriptive function and variables names that explain what they mean?\n
4. based on the code complexity of the changes, could the code be simplified without breaking its functionality? if so can you give example snippets?\n
5. Can you find any bugs, if so please explain and reference line numbers?\n
6. Do you see any code that could induce security issues?\n\n`

const STRUCTURED_INSTRUCTIONS = `
**IMPORTANT: You MUST respond with a valid JSON object in this exact format:**

\`\`\`json
{
  "summary": "Your overall review summary here (markdown formatted). Include general observations, recommendations, and overall assessment.",
  "inline_comments": [
    {
      "file": "path/to/file.ts",
      "line": 42,
      "comment": "Your specific comment about this line (can include markdown, code blocks, emojis)"
    }
  ]
}
\`\`\`

**CRITICAL JSON FORMATTING RULES:**
1. **Valid JSON**: The response MUST be valid JSON - no trailing commas, proper quotes everywhere
2. **Escape special characters**: In strings, you MUST escape:
   - Double quotes: Use \\" (e.g., "He said \\"hello\\"")
   - Newlines: Use \\n (e.g., "First line\\nSecond line")
   - Backslashes: Use \\\\ (e.g., "Path: C:\\\\folder")
3. **No line breaks in strings**: Never put actual line breaks inside JSON string values
4. **Markdown in strings**: You can use markdown but it must be properly escaped:
   - Code blocks: "Example: \`code\` or \`\`\`javascript\\ncode\\n\`\`\`"
   - Lists: "- Item 1\\n- Item 2\\n- Item 3"
5. **Complete arrays**: Always close the inline_comments array, even if truncated

**Content Rules:**
- The "summary" field contains your general review (can be empty string "" if no general observations)
- The "inline_comments" array contains specific issues found in the code
- Each inline comment MUST have exactly 3 fields: "file" (string), "line" (number), "comment" (string)
- **CRITICAL**: When you find bugs, security issues, or code problems, you MUST create an inline comment at the exact line where the issue is
- Use line numbers from the NEW file (after changes), not the old file
- If no specific issues found, use an empty array: "inline_comments": []
- Focus on actionable feedback
- For each issue found (bugs, security problems, etc.), create a separate inline_comment entry

**Example for a bug found at line 15:**
\`\`\`json
{
  "summary": "Found 1 critical bug that needs to be fixed.",
  "inline_comments": [
    {
      "file": "src/utils/helper.ts",
      "line": 15,
      "comment": "🐛 **Bug**: Potential null pointer exception. The variable \`user\` can be null here but is not checked before accessing \`user.name\`."
    }
  ]
}
\`\`\`

**Before sending your response:**
- Verify the JSON is valid (you can mentally parse it)
- Check all strings are properly escaped
- Ensure no trailing commas
- Confirm the structure matches exactly
`

const SYSTEM_PROMPT = 'You are a senior developer reviewing code changes. Format the response so it renders nicely in GitLab, with nice and organized markdown (use code blocks if needed), and send just the response no comments on the request, when answering include a short version of the question, so we know what it is.'

export const AI_MODEL_TEMPERATURE = 0.2

export interface BuildPromptParameters {
  oldFiles: OldFileVersion[]
  changes: Array<Pick<CommitDiffSchema, 'diff'>>
  commentMode?: CommentMode
}

// Unified prompt builder for all AI providers (using Vercel AI SDK format)
export const buildPrompt = ({ changes, oldFiles, commentMode = 'global' }: BuildPromptParameters): CoreMessage[] => {
  let modeInstructions = ''
  
  if (commentMode === 'structured') {
    modeInstructions = STRUCTURED_INSTRUCTIONS
  }
  
  const content = `
    As a senior developer, review the following code changes and answer code review questions about them. The code changes are provided as git diff strings.
    The entire file before the change is provided for context. Make sure to keep it as a reference when reviewing the changes.

    Files before changes:
    ${oldFiles.map(oldFile => JSON.stringify(oldFile)).join('\n\n')}

    Changes:
    ${changes.map(change => change.diff).join('\n\n')}

    ${QUESTIONS}
    ${modeInstructions}
    `

  return [
    { role: 'system', content: SYSTEM_PROMPT },
    { role: 'user', content }
  ]
}

const ERROR_ANSWER = 'I\'m sorry, I\'m not feeling well today. Please ask a human to review this code change.'

const DISCLAIMER = 'This comment was generated by an artificial intelligence duck.'

// Unified answer builder for all AI providers
export const buildAnswer = (text: string | undefined, error?: Error): string => {
  if (error) {
    return `${ERROR_ANSWER}\n\nError: ${error.message}`
  }
  if (!text) {
    return `${ERROR_ANSWER}\n\n${DISCLAIMER}`
  }
  
  return `${text}\n\n${DISCLAIMER}`
}
